### FizzBuzz
GET http://localhost:8080/api/fizzbuzz HTTP/1.1
Content-Type: application/json

{
    "num1": 2,
    "num2": 5,
    "limit": 15,
    "str1": "Fizz",
    "str2": "Buzz"
}

### FizzBuzz - Bad Request
GET http://localhost:8080/api/fizzbuzz HTTP/1.1
Content-Type: application/json

{
    "limit": 15,
    "str1": "Fizz"
}


### Top requests
GET http://localhost:8080/api/stats HTTP/1.1
Content-Type: application/json
